/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan3;

/**
 *
 * @author WINDOWS 8.1
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bil2 = new javax.swing.JTextField();
        Bil1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Btnkurang = new javax.swing.JButton();
        Btntambah = new javax.swing.JButton();
        Btnbagi = new javax.swing.JButton();
        Btnkali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Hasil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 270, 50, 30);

        jLabel2.setText("Bilangan 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 140, 60, 40);

        jLabel3.setText("Bilangan 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 60, 30);
        getContentPane().add(Bil2);
        Bil2.setBounds(150, 130, 120, 50);
        getContentPane().add(Bil1);
        Bil1.setBounds(150, 70, 120, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kalkulator Sederhana");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 20, 150, 50);

        Btnkurang.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        Btnkurang.setText("-");
        Btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkurang);
        Btnkurang.setBounds(130, 230, 40, 30);

        Btntambah.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        Btntambah.setText("+");
        Btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntambahActionPerformed(evt);
            }
        });
        getContentPane().add(Btntambah);
        Btntambah.setBounds(80, 230, 40, 30);

        Btnbagi.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        Btnbagi.setText(":");
        Btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(Btnbagi);
        Btnbagi.setBounds(290, 230, 40, 30);

        Btnkali.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        Btnkali.setText("X");
        Btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkali);
        Btnkali.setBounds(230, 230, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Operator");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 190, 80, 30);
        getContentPane().add(Hasil);
        Hasil.setBounds(160, 310, 80, 50);

        setBounds(0, 0, 416, 411);
    }// </editor-fold>//GEN-END:initComponents

    private void BtntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntambahActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil1 = bilangan1 + bilangan2;
        Hasil.setText(String.valueOf(hasil1));
    }//GEN-LAST:event_BtntambahActionPerformed

    private void BtnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkurangActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil2 = bilangan1 - bilangan2;
        Hasil.setText(String.valueOf(hasil2));
    }//GEN-LAST:event_BtnkurangActionPerformed

    private void BtnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkaliActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil3 = bilangan1 * bilangan2;
        Hasil.setText(String.valueOf(hasil3));
    }//GEN-LAST:event_BtnkaliActionPerformed

    private void BtnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbagiActionPerformed
        double bilangan1 = Double.parseDouble(Bil1.getText());
        double bilangan2 = Double.parseDouble(Bil2.getText());
        double hasil4 = bilangan1 / bilangan2;
        Hasil.setText(String.valueOf(hasil4));
    }//GEN-LAST:event_BtnbagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bil1;
    private javax.swing.JTextField Bil2;
    private javax.swing.JButton Btnbagi;
    private javax.swing.JButton Btnkali;
    private javax.swing.JButton Btnkurang;
    private javax.swing.JButton Btntambah;
    private javax.swing.JTextField Hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
